version: '3'
services:
  rabbitmq1:
    image: rabbitmq:3-management
    hostname: my-rabbit1
    environment:
      RABBITMQ_DEFAULT_USER: user1
      RABBITMQ_DEFAULT_PASS: password1
    ports:
      - "4369:4369"
      - "5671-5672:5671-5672"
      - "15671-15672:15671-15672"
      - "15691-15692:15691-15692"
      - "25672:25672"

  rabbitmq2:
    image: rabbitmq:3-management
    hostname: my-rabbit2
    environment:
      RABBITMQ_DEFAULT_USER: user2
      RABBITMQ_DEFAULT_PASS: password2
    ports:
      - "4370:4369"
      - "5673-5674:5671-5672"
      - "15673-15674:15671-15672"
      - "15693-15694:15691-15692"
      - "25673:25672"
